### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by LK4D4** [godbus/dbus#11]
Hello, guys, how about v1.0.1? I see that you've fixed `vet` warnings since last release for example.
Thanks!

**Comment by philips** [comment]
Hrm, good idea. I will do this now.

**Comment by philips** [comment]
https://github.com/godbus/dbus/releases/tag/v2

**Comment by philips** [comment]
Thanks for the reminder. Let me know if I am slacking again in the future :-P

**Comment by LK4D4** [comment]
@philips No problem :) Thanks for tag!
