### ISSUE TITLE
Semantic tag v5.0.0

### ISSUE THREAD

**Issue by amenzhinsky** [godbus/dbus#126]
Hi guys, can someone add `v5.0.0` tag on top of `v5.0` to follow semantic versioning, it seems like without this modules-aware go get fails to get the 5th release.

https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

```
% go get -v github.com/godbus/dbus@v5.0
go get github.com/godbus/dbus@v5.0: no matching versions for query "v5.0"

 % go get -v github.com/godbus/dbus@v5.0.0
go get github.com/godbus/dbus@v5.0.0: unknown revision v5.0.0
```

**Comment by jsouthworth** [comment]
I've tagged the release as v5.0.0.
