### ISSUE TITLE
Conflicting tags v5.0 and v5.0.0

### ISSUE THREAD

**Issue by svenschwermer** [godbus/dbus#128]
It seems like [dep](https://github.com/golang/dep) is really confused about the tags `v5.0` and `v5.0.0` that don't seen to be pointing at the same commit. Is that intentional?

**Comment by svenschwermer** [comment]
I think it's ok to have them both, but `v5.0` points to `66d97aec3384421e393c2a76b770a1b5c31d07a8` whereas `v5.0.0` points to `2ff6f7ffd60f0f2410b3105864bdd12c7894f844`. Shouldn't they refer to the same commit? I think that's the part that confuses `dep`.

**Comment by jsouthworth** [comment]
I reworked the tags. v5.0.0 now points to 66d97ae and v5.0.1 points to 2ff6f7f
