### ISSUE TITLE
Stale godoc; quick fix?

### ISSUE THREAD

**Issue by whereswaldon** [godbus/dbus#131]
The documentation [here](https://github.com/godbus/dbus/blob/master/conn.go#L384) doesn't appear to correspond to the function underneath it. The names don't match, but also it's unclear whether the code is related to the docs. Seems like the `outWorker` may properly be the docs for [`send`](https://github.com/godbus/dbus/blob/master/conn.go#L415).

**Comment by jsouthworth** [comment]
outWorker was eliminated due to it being too complex for what it was doing. It looks like the doc string was missed during that rework.

**Comment by z3ntu** [comment]
I'm guessing this is fixed now with #134 ?

**Comment by jsouthworth** [comment]
Looks like it, thanks!
