### ISSUE TITLE
How to properly convert "Struct of (UInt16, UInt16)"

### ISSUE THREAD

**Issue by z3ntu** [godbus/dbus#146]
I have a D-Bus interface with the following method (taken from the introspection xml)
```xml
    <method name="getDPI">
      <arg direction="out" type="(qq)"/>
    </method>
```
The following code works but in my opinion is quite ugly
```go
        var interf []interface{}
	err := dev.DbusObject.Call(DeviceInterface+".getDPI", 0).Store(&interf)
	if err != nil {
		return DPI{}, err
	}
	dpi := DPI{
		interf[0].(uint16), interf[1].(uint16),
	}
```
and DPI is just defined as
```go
type DPI struct {
	x uint16
	y uint16
}
```

Is there a better way to do this (using `[]uint16` as type for the `interf` variable leds to the error `dbus.Store: type mismatch: slice: cannot convert a value of []interface {} into []uint16`

**Comment by amenzhinsky** [comment]
Did you try to export `x` and `y`? 
The reflect package cannot access private attributes.

**Comment by z3ntu** [comment]
Thanks, that seems to work!

```go
        var dpi DPI
	err := dev.DbusObject.Call(DeviceInterface+".getDPI", 0).Store(&dpi)
	if err != nil {
		return DPI{}, err
	}
	return dpi, nil
```
```go
type DPI struct {
	X uint16
	Y uint16
}
```
