### ISSUE TITLE
Investigate array allocation in the decoder

### ISSUE THREAD

**Issue by jsouthworth** [godbus/dbus#148]
The decoder currently doesn't preallocate the proper size for the arrays it is decoding. #147 is a first step at making this better. It solves the over allocation for a significant class of arrays but may over allocate for others due to the way 'append' works. We should try to allocate exactly the decoded size of the array.

**Comment by amenzhinsky** [comment]
The over-allocating was caused by improper array length argument treatment: 

https://dbus.freedesktop.org/doc/dbus-specification.html
> Arrays are marshalled as a UINT32 n giving the length of the array data in bytes
