### ISSUE TITLE
SystemBusPrivate doesn't return a working conn.

### ISSUE THREAD

**Issue by james-lawrence** [godbus/dbus#15]
to get a working conn need to invoke:

```
    conn, err := dbus.SystemBusPrivate()
    if err != nil {
        return err
    }
    if err = conn.Auth(nil); err != nil {
        conn.Close()
        return err
    }
    if err = conn.Hello(); err != nil {
        conn.Close()
        return  err
    }
```

**Comment by philips** [comment]
The problem is that you don't want to have to do the Auth and Hello?

**Comment by james-lawrence** [comment]
The problem is shouldn't have to. expected it to return a working connection. instead I got a broken one without any documentation as to why on the method.

**Comment by purpleidea** [comment]
I *just* figured out there were private/shared buses for both session and system. This explains why different parts of the code are receiving each other's messages! In any case, I couldn't get the PrivateBus to work, until I dug through the code and found this:

```
func SystemBus() (conn *Conn, err error) {
	systemBusLck.Lock()
	defer systemBusLck.Unlock()
	if systemBus != nil {
		return systemBus, nil
	}
	defer func() {
		if conn != nil {
			systemBus = conn
		}
	}()
	conn, err = SystemBusPrivate()
	if err != nil {
		return
	}
	if err = conn.Auth(nil); err != nil {
		conn.Close()
		conn = nil
		return
	}
	if err = conn.Hello(); err != nil {
		conn.Close()
		conn = nil
	}
	return
}
```

Which is approximately what @james-lawrence is saying.

So I do agree some doc/api fixes are in order... Will test this all tomorrow!

**Comment by purpleidea** [comment]
Incidentally, if you're *not* using private buses, then if you close the connection, everyone who is on the shared bus will see it closed!

**Comment by kyrofa** [comment]
@purpleidea indeed, the [docs for Close()](https://godoc.org/github.com/godbus/dbus#Conn.Close) say to not call it on shared connections.

**Comment by purpleidea** [comment]
@philips would you accept a patch to either:
1) Change the API so that SystemBusPrivate returns something usable, and creates a SystemBusBase which does what SystemBusPrivate does?

or
2) Add a SystemBusPrivateReady method that returns the usable thing we expect, similar to SystemBus.

I'd prefer the first choice, because it fixes the API to make it most logical.

LMK

**Comment by purpleidea** [comment]
I have this snippet in my code in the meantime now:

```
func SystemBusPrivateUsable() (conn *dbus.Conn, err error) {
	conn, err = dbus.SystemBusPrivate()
	if err != nil {
		return nil, err
	}
	if err = conn.Auth(nil); err != nil {
		conn.Close()
		conn = nil
		return
	}
	if err = conn.Hello(); err != nil {
		conn.Close()
		conn = nil
	}
	return conn, nil // success
}
```

Happy to merge it upstream if someone is interested.

**Comment by philips** [comment]
@purpleidea Is there another dbus API that we can compare this Private/Base solution to?

**Comment by purpleidea** [comment]
> @purpleidea Is there another dbus API that we can compare this Private/Base solution to?

@philips I'm sorry, I'm not sure if I understand what you're asking. The point is to make using the "Private" version of the bus a drop in replacement for the regular dbus.SystemBus() call.

**Comment by philips** [comment]
@purpleidea I am asking how does a C or python or Java library handle this?

**Comment by purpleidea** [comment]
On Mon, Feb 22, 2016 at 5:34 PM, Brandon Philips <notifications@github.com>
wrote:

> @purpleidea <https://github.com/purpleidea> I am asking how does a C or
> python or Java library handle this?


Oh, typically AFAIK there is a private (true/false) keyword on the main
initializer... This would also break API. I'm actually file with the two
bus objects, but as I said, the naming is confusing, and we lack the easy
private option. Python:

https://dbus.freedesktop.org/doc/dbus-python/api/dbus._dbus.Bus-class.html#__new__

**Comment by tomkcook** [comment]
Just to say, I have also been burned by this.  At least an update to the API docs to say, "This doesn't return a working connection in the same way `SystemBus()` does, you need to call `Auth()` and `Hello()` on it before you use it" would be nice.

**Comment by james-lawrence** [comment]
I agree, that is the minimum that should be done.

**Comment by ozmy** [comment]
I ask if it is possible to put in example a working sample code for dbus.SystemBusPrivate. Thank you.

**Comment by jsouthworth** [comment]
Are the changes in #140 sufficient?

**Comment by james-lawrence** [comment]
believe so

**Comment by ozmy** [comment]
Unfortunately, I can not run my code.
At e03 print, the code hangs and no longer responds.
Maybe you know the reasons for this behavior?
Thank you in advance

`package main

import (
	"fmt"
	"log"
	"net"
	"github.com/godbus/dbus"
)

func AEnableIp (ipin string) {
	
	ipaddr := net.ParseIP(ipin)

	stipaddr := fmt.Sprintf("%s", ipaddr)

	var CallMethod string = "org.fedoraproject.FirewallD1.config.zone.addSource string:'"+stipaddr+"'"

	fmt.Println(CallMethod)

	log.Println("e01")

	//i use dbus.SystemBusPrivate or dbus.SystemBus with the same effect
	conn, err := dbus.SystemBusPrivate()
	//conn, err := dbus.SystemBus()

	log.Println(conn)
	if err != nil {
		panic(err)
	}

	log.Println("e02")

	obj := conn.Object("org.fedoraproject.FirewallD1", "/org/fedoraproject/FirewallD1/config/zone/9")

	log.Println("e03")

	call := obj.Call(CallMethod, 0)

	log.Println("e04")
	if call.Err != nil {
		panic(call.Err)
	}
}

func main() {
	var ipset string = "192.168.200.200"
	AEnableIp(ipset)
}

`

**Comment by ozmy** [comment]
Unfortunately, I can not run my code.
At e03 print, the code hangs and no longer responds.
Maybe you know the reasons for this behavior?
Thank you in advance

package main

import (
	"fmt"
	"log"
	"net"
	"github.com/godbus/dbus"
)

func AEnableIp (ipin string) {

	ipaddr := net.ParseIP(ipin)

	stipaddr := fmt.Sprintf("%s", ipaddr)

	var CallMethod string = "org.fedoraproject.FirewallD1.config.zone.addSource string:'"+stipaddr+"'"

	fmt.Println(CallMethod)

	log.Println("e01")

	//i use dbus.SystemBusPrivate or dbus.SystemBus with the same effect
	conn, err := dbus.SystemBusPrivate()
	//conn, err := dbus.SystemBus()

	log.Println(conn)
	if err != nil {
		panic(err)
	}

	log.Println("e02")

	obj := conn.Object("org.fedoraproject.FirewallD1", "/org/fedoraproject/FirewallD1/config/zone/9")

	log.Println("e03")

	call := obj.Call(CallMethod, 0)

	log.Println("e04")
	if call.Err != nil {
		panic(call.Err)
	}
}

func main() {
	var ipset string = "192.168.200.200"
	AEnableIp(ipset)
}

**Comment by jsouthworth** [comment]
The request was to add documentation on how to use SystemBusPrivate. See the example here: https://godoc.org/github.com/godbus/dbus#SystemBusPrivate

**Comment by tomkcook** [comment]
Stumbled across the changes in the godoc today.  Looks good, thank you.

**Comment by guelfey** [comment]
Adressed in https://github.com/godbus/dbus/pull/140.
