### ISSUE TITLE
Move AddMatchSignal from BusObject to Conn

### ISSUE THREAD

**Issue by amenzhinsky** [godbus/dbus#154]
`BusObject` interface defines:
```
AddMatchSignal(iface, member string, options ...MatchOption) *Call
RemoveMatchSignal(iface, member string, options ...MatchOption) *Call
```

I think they should be moved to `*Conn` since they work only with `conn.BusObject()` but available for all objects and their paths are not used in the match expressions.

Also it'd be better to change the signature to `AddMatchSignal(options ...MatchOption)` because it's more flexible and can be used say to subscribe to all signals or to signals from a particular sender.

Of course existing methods have to remain and be marked as deprecated.

What do you think on this?

**Comment by jsouthworth** [comment]
This sounds like a good addition to me.
