### ISSUE TITLE
Offer a context-aware shutdown

### ISSUE THREAD

**Issue by mvdan** [godbus/dbus#159]
Imagine a Go program exposes a DBus service, and wants to properly shutdown when the user hits ^C. It should terminate very soon, but without dropping any ongoing requests.

The `net/http` package uses a shutdown method for this: https://golang.org/pkg/net/http/#Server.Shutdown

While the HTTP server is being shutdown, existing requests are finished until the context is canceled, and new requets aren't accepted.

Could we have a `Shutdown(context.Context) error` on `Conn` too? I know there's `Close() error`, but I assume that immediately terminates the entire connection. 

Perhaps this doesn't make sense for DBus; I'm not an expert with it. But, intuitively, it seems possible.

**Comment by jsouthworth** [comment]
Shutdown on DBus is tricky, particularly if activation is being used. This will need some considerable design thought as to the right way to handle it. If you have ideas then please open a PR as a starting point or add comments here.

**Comment by mvdan** [comment]
Fair enough, thanks. Googling a bit more, it seems like everyone simply closes the connection, and relies on names being freed to keep things working as expected.

I don't have a particular design in mind. If you think it's tricky, and noone else is doing this with DBus, then it's probably not worth keeping this issue open.
