### ISSUE TITLE
Add some form of debug option

### ISSUE THREAD

**Issue by mvdan** [godbus/dbus#160]
I have a program that exposes a DBus service. While implementing the service, I've messed up types and signatures a few times, and that was hard to debug.

To properly debug what was going on, I had to modify the dbus library to add debug prints, to see what calls were being made, which objects were being looked up, what responses were being sent out, et cetera.

It would be great if the library had some built-in support for debugging or extra logging like this, so I don't have to modify it each time.

The simplest form would be a `ConnOption` which turns on debugging, and then all those details get printed out via the `log` package.

A perhaps more versatile API would be a series of `ConnOption`s which set up callback functions for each kind of activity. For example:

```
conn, err := dbus.SessionBusPrivate(dbus.WithLookupInspector(func(v interface{}) {
    log.Println("lookup:", v)
}))
```

The name and `v interface{}` are just made up for the sake of the example.

**Comment by jsouthworth** [comment]
This seems reasonable. Would you be up to contributing the code that adds the debugging information you are looking for?

**Comment by mvdan** [comment]
Sure! Some guidance on the API would be good, though. What do you think would work best? I'm not familiar with the design and codebase at all.

**Comment by jsouthworth** [comment]
I think you have the right idea in the example there. That is, make the options ConnOption functions.
