### ISSUE TITLE
Travis-CI config looks like it is trying to test on multiple architectures but doesn't

### ISSUE THREAD

**Issue by jhenstridge** [godbus/dbus#162]
When submitting a PR, I noticed that it expanded into a large number of Travis jobs based on the Go version and a TARGET environment variable.  I suspect the intent was to test on multiple architectures.

However, that variable isn't used by the Go compiler for cross compilation (it wants GOOS/GOARCH), and doesn't seem to influence Travis either: all builds seem to be on arm64.  So it looks like it is just repeating the same tests 5 times.

**Comment by jsouthworth** [comment]
Looks like this is the case. I'll do some investigation into how to make this work properly.
