### ISSUE TITLE
No way to change a property from my program

### ISSUE THREAD

**Issue by Rudd-O** [godbus/dbus#188]
I've registered properties and exported them successfully, and I can query them via D-Bus.

The problem arises when my program, because of internal state changes, must expose these property changes back to the bus.

How does one do this?  I tried *Properties.Set() and it had no effect.  I also tried changing the prop.Prop's value to a dbus.NewVariant() and the program just disconnected from the bus.

Help!

**Comment by jsouthworth** [comment]
Seems to be working for me when I modify the example code like so:
```
iff --git a/_examples/prop.go b/_examples/prop.go
index 7053e2a..46aa917 100644
--- a/_examples/prop.go
+++ b/_examples/prop.go
@@ -3,6 +3,7 @@ package main
 import (
        "fmt"
        "os"
+       "time"
 
        "github.com/godbus/dbus/v5"
        "github.com/godbus/dbus/v5/introspect"
@@ -64,6 +65,8 @@ func main() {
                "org.freedesktop.DBus.Introspectable")
        fmt.Println("Listening on com.github.guelfey.Demo / /com/github/guelfey/Demo ...")
 
+       time.Sleep(10 * time.Second)
+       props.SetMust("com.github.guelfey.Demo", "SomeInt", 20)
        c := make(chan *dbus.Signal)
        conn.Signal(c)
        for _ = range c {

```

and run it I see the following in `dbus-monitor --session`:

```
signal time=1578703664.105145 sender=:1.50 -> destination=(null destination) serial=3 path=/com/github/guelfey/Demo; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "com.github.guelfey.Demo"
   array [
      dict entry(
         string "SomeInt"
         variant             int32 20
      )
   ]
   array [
   ]

```

Can you provide a reproducer for the problem that you see?

**Comment by Rudd-O** [comment]
Oh.  I see.  I have to keep the *Props structure around.  OK.  Thanks.
