### ISSUE TITLE
prop.Set(...) returns nil error value that causes panic when printing panic

### ISSUE THREAD

**Issue by Rudd-O** [godbus/dbus#189]
Set() returns a *dbus.Error that is nil.  As soon as it is returned to the caller's caller, err != nil "become true", and panicking at this point with panic(err) causes a crash hard to debug.

```
func (b *Bus) UpdateComDevice(comDevice string) error {
	err := b.props.Set(b.Interface(), "ComDevice", dbus.MakeVariant(comDevice))
	fmt.Println(err == nil)  // true
	return err
}
...
	if err := b.UpdateComDevice(cec.ComDevice()); err != nil {
		fmt.Printf("\n          %t\n", err)
	fmt.Println(err == nil)  // false
		panic(err)
	}
```

See first answer here: https://stackoverflow.com/questions/54368951/panic-when-printing-a-nil-error-in-a-struct .  I have to type-assert in order to bypass this bug.

**Comment by Rudd-O** [comment]
This is my workaround code:

```
	if err := b.UpdateComDevice(cec.ComDevice()); err != nil {
		fmt.Printf("           %T", err)
		if derr, ok := err.(*dbus.Error); ok {
			if derr != nil {
				panic(derr)
			}
		} else {
			panic(err)
		}
		os.Exit(1)
	}
```

**Comment by jsouthworth** [comment]
This is a side effect of how interfaces work. Your UpdateComDevice function is encapsulating the value {'*dbus.Error', nil} in an error interface. This can be illustrated simply using like https://play.golang.org/p/SCmJLuFOGdV.

The way 'c' in the above example handles the error will solve the problem for you

**Comment by Rudd-O** [comment]
It's certainly unexpected behavior.  You don't expect to get a wrapped
error that way — the normal thing is to return something like an error,
not a *dbus.Error.

**Comment by jsouthworth** [comment]
It isn't unexpected if one knows how interfaces work. For the standard exporter we require exported the function to return a concrete '*dbus.Error' to be selected for export. Changing this will break existing clients so we won't do that. The '(*prop.Properties).Set' method is meant for export over DBus, so it has this signature. One could add a helper method to the 'prop.Properties' structure to hide the boilerplate if it is too onerous. A patch doing that would be welcome.

**Comment by Rudd-O** [comment]
Can you at least *document* this quirk?  Thanks.

**Comment by jsouthworth** [comment]
It is not a quirk. It is just how interfaces work. If one returns a concrete type as an interface, that interface is not nil even if the concrete type is. The code in the dbus library isn't the problem, the code that you wrote is where the issue is. Returning a concrete type as an error may not be completely idiomatic but there isn't anything wrong with doing it.

**Comment by guelfey** [comment]
To add on this: `Set` is mostly there to be used by `Export` and thus fits the signature it expects, returning a concrete *dbus.Error. If you want to set a property from application code, `SetMust` is more appropriate.

**Comment by guelfey** [comment]
(And as @jsouthworth explained, this is just a "quirk" of how interfaces work in Go.)
