### ISSUE TITLE
How to parse property (yy)?

### ISSUE THREAD

**Issue by z3ntu** [godbus/dbus#191]
Hi, I have a dbus property which is the defined the following:
```xml
<property access="read" type="(yy)" name="MyProperty">
```
so it's a `Struct of (Byte, Byte)`.
According to the docs, a D-Bus byte is mapped to the go type byte. I have the following Go code:
```go
variant, err := dev.DbusObject.GetProperty(DeviceInterface + ".MatrixDimensions")
if err != nil {
	return MatrixDimensions{}, err
}
```
Looking at the debugger, the `variant` value returned by this code is the following:
![image](https://user-images.githubusercontent.com/3768500/72378162-256b9280-3711-11ea-88dd-ddc6d1ee64de.png)
Trying to cast this value to a byte array using `variant.Value().([]byte)` results in `panic: interface conversion: interface {} is []interface {}, not []uint8`.
(note, the things I've written above from here were from seeking help on how to do it, I've found a way to convert the values now ~~but I'm hoping there's a nicer way~~ (the last part of this note is also not really valid anymore))
Apparently I can convert this value to a `[]byte` with the following code (courtesy of https://stackoverflow.com/a/44027953/3527128):
```go
s := make([]byte, 2)
for i, v := range variant.Value().([]interface{}) {
	s[i] = v.(byte)
}
```
So now I can use the following - which doesn't look too bad :)
```go
variant, err := dev.DbusObject.GetProperty(DeviceInterface + ".MyProperty")
if err != nil {
	return MyProperty{}, err
}
values := variant.Value().([]interface{})
return MyProperty{values[0].(byte), values[1].(byte)}, nil
```
I'm still posting this because I want 1. other people to know that this is possible (an example in the repo would help there as well!) and 2. ask if there's an even better way that I don't know of yet.
Thanks for godbus, it's pretty slick!

**Comment by jsouthworth** [comment]
If you don't want to mess around with the Variants you can get properties by using the normal Call method as well.
```
...
var s []byte
err := obj.Call("org.freedesktop.DBus.Properties.Get", 0, DeviceInterface, "MyProperty").Store(&s)
...
```

**Comment by jsouthworth** [comment]
I've opened a PR, #199 that should make this easier. It does two things, it adds a StoreProperty method to objects so one can unpack the property directly, and it adds a Store method to the Variant structure so one may unpack a variant using the builtin reflection mechanism. Would this help your case?
