### ISSUE TITLE
Question: how to read hostname using dbus

### ISSUE THREAD

**Issue by yboaron** [godbus/dbus#194]
Hi all,

I'm new to GOLANG, I need to write a GO function that returns hostname (using dbus).

It should be something similar  to [1] python script 

Many thanks in advance
Yossi

[1] 
#!/usr/bin/env python
import dbus
NM_DBUS_SVC = 'org.freedesktop.NetworkManager'
NM_SETTINGS_DBUS_OBJ = '/org/freedesktop/NetworkManager/Settings'
DBUS_PROP_IFACE = 'org.freedesktop.DBus.Properties'
bus = dbus.SystemBus()
nm_settings = bus.get_object(
    NM_DBUS_SVC,
    NM_SETTINGS_DBUS_OBJ)
prop_iface = dbus.Interface(
    nm_settings,
    dbus_interface=DBUS_PROP_IFACE)
print(
    prop_iface.Get(
        'org.freedesktop.NetworkManager.Settings',
	'Hostname'))

**Comment by jsouthworth** [comment]
More or less translated verbatim from your python code:
```
package main

import (
	"fmt"
	"github.com/godbus/dbus"
	"log"
)

const (
	NM_DBUS_SVC          = "org.freedesktop.NetworkManager"
	NM_SETTINGS_DBUS_OBJ = "/org/freedesktop/NetworkManager/Settings"
	DBUS_PROP_IFACE      = "org.freedesktop.DBus.Properties"
)

func main() {
	bus, err := dbus.ConnectSystemBus()
	if err != nil {
		log.Fatal(err)
	}
	defer bus.Close()
	nmSettings := bus.Object(NM_DBUS_SVC, NM_SETTINGS_DBUS_OBJ)
	var hostname string
	err = nmSettings.Call(DBUS_PROP_IFACE+".Get", 0,
		"org.freedesktop.NetworkManager.Settings",
		"Hostname").
		Store(&hostname)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(hostname)
}

```
