### ISSUE TITLE
how to parse a(ubay)

### ISSUE THREAD

**Issue by maltegrosse** [godbus/dbus#197]
Hi all,
anyone has an idea how to parse this?
I guess its just a char array, 
`.([]string)`
`.([][]string)`
`.([][]dbus.Variant)`
doesnt work, only
`.([][]interface{})`

**Comment by jsouthworth** [comment]
I haven't tried it, but I think something like:
```
type data struct {
    First     uint32
    Second    bool
    Third     []byte
}
var value []data
...
call.Store(&value)
...
```
Will probably works as it matches that DBus type signature.

**Comment by jsouthworth** [comment]
This does seem to work here is a test program:
```
package main

import (
	"fmt"
	"os"

	"github.com/godbus/dbus"
)

type data struct {
	First  uint32
	Second bool
	Third  []byte
}

type foo []data

func (f foo) Data() ([]data, *dbus.Error) {
	return []data(f), nil
}

func main() {
	conn, err := dbus.ConnectSessionBus()
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	f := make(foo, 10)
	conn.Export(f, "/com/github/godbus/test", "com.github.godbus.Test")
	reply, err := conn.RequestName("com.github.godbus.Test",
		dbus.NameFlagDoNotQueue)
	if err != nil {
		panic(err)
	}
	if reply != dbus.RequestNameReplyPrimaryOwner {
		fmt.Fprintln(os.Stderr, "name already taken")
		os.Exit(1)
	}

	var data []data
	o := conn.Object("com.github.godbus.Test", "/com/github/godbus/test")
	c := o.Call("com.github.godbus.Test.Data", 0)
	err = c.Store(&data)
	if err != nil {
		panic(err)
	}
	fmt.Println(data)
}
```

**Comment by maltegrosse** [comment]
thank you, yes, the strcut seems to be correct, but iam still not able to parse it.
Its a property - so I call it with the `GetProperty(p string) (Variant, error)` method. 

Can you test this too?

**Comment by jsouthworth** [comment]
There are a few options here:
1. If you don't want to mess around with the Variants you can get properties by using the normal Call method as well.
```
...
var s []byte
err := obj.Call("org.freedesktop.DBus.Properties.Get", 0, DeviceInterface, "MyProperty").Store(&s)
...
```

2. You could use the Store function with the variant's value to unpack it. Using the same structure definition as before:
```
...
	err = dbus.Store([]interface{}{v.Value()}, &data)
	if err != nil {
		panic(err)
	}
	fmt.Println(data)
...
```

It is probably worth creating a helper method on Variants to do this as one could use the internal "store" functions and avoid some of the inefficiency associated with the existing public interface. I'd welcome a PR for this change if you are so inclined.

**Comment by jsouthworth** [comment]
I've created a PR that has some helper methods to make this a bit easier. Would this help solve the problem you are having?

**Comment by maltegrosse** [comment]
sorry for getting back to u so late - i somehow crashed my development device and couldnt test.
but this feature looks great - thank you
