### ISSUE TITLE
How to listen for signals?

### ISSUE THREAD

**Issue by Tockra** [godbus/dbus#211]
Hi guys,

I have a dbus doc here, which tells me there is a signal called, when the state of the GPIO-Ports changes:

Signal: GpioChangedNTF
This notification is emitted when the value of a GPIO changes.

Type | Name | Direction | Description
-- | -- | -- | --
string | Gpio | out | The following GPIOs are supported:"PIN23""PIN15"
bool | Value | out | Value of the GPIO (true or false)

So know I tried:
```go
dd, err := dbus.SystemBus()
	if err != nil {
		return nil, errors.New("ConnectGPIODBusError: " + err.Error())
	}

	c := make(chan *dbus.Signal)
	dd.Signal(c)

	for sig := range c {
		log.Println("HEL: ", sig)
	}
```

and I just get one signal:
```bash
2020/07/22 11:26:32 HEL:  &{org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.NameAcquired [:1.477]}
```
Does I do something wrong?

T

**Comment by jhenstridge** [comment]
You want to call the connection's `AddMatchSignal` method to indicate what signal you're interested in.  The D-Bus daemon will only deliver signals that you've expressed interest in.

You probably want something like:

    err := conn.AddMatchSignal(dbus.WithMatchSender('bus name'), dbus.WithMatchObjectPath('object path'), dbus.WithMatchInterface('interface'))

... substituting in the details of the service you're listening to.
