### ISSUE TITLE
Wildcard in filter for dbus events?

### ISSUE THREAD

**Issue by Evidlo** [godbus/dbus#218]
I'm listening for dbus events emitted from a particular application.  In older versions of this application, the filter below worked well for getting events I'm interested in.

	var rules = []string{
		"interface='org.freedesktop.DBus.Properties',path='/org/freedesktop/network1/link/_34',member='PropertiesChanged'",
	}

Unfortunately, in the latest release of the application, the `_34` part of the path is a random number.  It doesn't seem like dbus filters have any sort of wildcard.  Is there a way I can grab all these events with one filter?

Github issue for context: https://github.com/Evidlo/remarkable_news/pull/17

**Comment by jsouthworth** [comment]
I think you want "path_namespace" instead of "path".  https://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-routing-match-rules

**Comment by Evidlo** [comment]
Thanks
