### ISSUE TITLE
equivarent to python's Interface?

### ISSUE THREAD

**Issue by mattn** [godbus/dbus#22]
I'm porting below's python script into godbus.

``` python
bus = dbus.SessionBus ()
from os.path import expanduser
player = bus.get_object ("org.mpris.MediaPlayer2.rhythmbox", "/org/mpris/MediaPlayer2")
iface = dbus.Interface (player, "org.freedesktop.DBus.Properties")

track = iface.Get("org.mpris.MediaPlayer2.Player","Metadata").get(dbus.String(u'xesam:artist'))[0] + " - " + iface.Get("org.mpris.MediaPlayer2.Player","Metadata").get(dbus.String(u'xesam:title'))
```

what is equivarent to python's `Interface` ?

**Comment by guelfey** [comment]
There's no direct equivalent; you'd use https://pkg.go.dev/github.com/godbus/dbus/v5@v5.0.6#Conn.Object to get the object and then call https://pkg.go.dev/github.com/godbus/dbus/v5@v5.0.6#Object.Call on it with "org.freedesktop.DBus.Properties.Get"; for properties, there's actually the special helper https://pkg.go.dev/github.com/godbus/dbus/v5@v5.0.6#Object.GetProperty now.
