### ISSUE TITLE
How to test

### ISSUE THREAD

**Issue by abergmeier** [godbus/dbus#228]
Thanks for this pure Go dbus implementation. It is amazing. The only gripe I have is it does not seem to compile on FreeBSD.

Now, maybe I am missing something but using dbus, I am somewhat lost how to write tests or how to setup a Mock connection. Any tips would be appreciated.

**Comment by jsouthworth** [comment]
I don't have a FreeBSD machine handy to debug this, but if you can get it working PRs are welcome.

**Comment by Jacalz** [comment]
I think this might have been fixed with https://github.com/godbus/dbus/commit/efee8394fa9a426004eb24eed1dee80f5efd90af if you were using FreeBSD 13 when trying to compile it. I know that the project compiles without issues on FreeBSD 11 and 12 without issues, and on 13 after that change :slightly_smiling_face:

**Comment by guelfey** [comment]
As mentioned, build on FreeBSD should be fixed. For testing, that depends on what exactly you actually want to test. If I understand you correctly and you want to mock away the D-Bus method calls for your test, the best way is probably to implement a mock for the [BusObject interface](https://pkg.go.dev/github.com/godbus/dbus/v5#BusObject), or structure your application code such that you actually have another interface that abstracts the method calls completely and mock this interface.

**Comment by twpayne** [comment]
You can add a GitHub Action to test on FreeBSD, see https://gopheradvent.com/calendar/2021/how-chezmoi-implements-cross-platform-ci/ for instructions (tl;dr use Vagrant on macOS).

**Comment by guelfey** [comment]
FWIW thre is also a FreeBSD job using Cirrus now: https://github.com/godbus/dbus/pull/361
