### ISSUE TITLE
Go struct to dbus struct - does ordering matter?

### ISSUE THREAD

**Issue by js-sketch** [godbus/dbus#234]
As an example:

Given dbus type `(si)`, does the corresponding Go struct have to be:

 ```go
struct {
    A string
    B int64
}
```

Or would

 ```go
struct {
    B int64
    A string
}
```

also be feasible?

I assume the latter is not feasible, as it'd lead to ambiguity. If my assumption is correct, then could it be mentioned in the Conversion rules of the docs that the ordering of the struct members in Go matter?

**Comment by guelfey** [comment]
Yes, ordering of structs matters - they have to be exactly in the same order to match a D-Bus struct since they're all ordered. I'll clarify in the docs.
