### ISSUE TITLE
Question: Making method calls after I started Eavesdrop()-ing

### ISSUE THREAD

**Issue by AdamantGarth** [godbus/dbus#305]
I'm very new to DBus and don't understand much, but I want to add a custom action handler for some notifications and for that I need to know the destination PID. My current code, edited from eavesdropping example:

```go
package main

import (
	"fmt"
	"os"

	"github.com/godbus/dbus/v5"
)

func main() {
	conn, err := dbus.ConnectSessionBus()
	if err != nil {
		fmt.Fprintln(os.Stderr, "Failed to connect to session bus:", err)
		os.Exit(1)
	}
	defer conn.Close()

	call := conn.BusObject().Call("org.freedesktop.DBus.AddMatch", 0, "eavesdrop='true',type='signal',interface='org.freedesktop.Notifications',member='ActionInvoked'")
	if call.Err != nil {
		fmt.Fprintln(os.Stderr, "ERROR: Failed to add match:", call.Err)
		os.Exit(1)
	}


	c := make(chan *dbus.Message, 10)
	conn.Eavesdrop(c)
	fmt.Println("Listening for activated notifications...")
	for notification := range c {
		fmt.Println("Got notification!")
		dest := notification.Headers[dbus.FieldDestination].String()
		call = conn.BusObject().Call("org.freedesktop.DBus.GetConnectionUnixProcessID", 0, dest)
		if call.Err != nil {
			fmt.Fprintln(os.Stderr, "ERROR: Failed to get destination PID:", call.Err)
			continue
		}
		var pid uint32
		err = call.Store(&pid)
		if err != nil {
			fmt.Fprintln(os.Stderr, "ERROR: Failed to store destination PID:", err)
			continue
		}
		fmt.Println("PID:", pid)
	}
}
```

Looks like program just hangs on the `call = conn.BusObject().Call("org.freedesktop.DBus.GetConnectionUnixProcessID", 0, dest)` line. I suspect that is because of something that eavesdropping does.

So, is there any way for me to make the `GetConnectionUnixProcessID` call after I started eavesdropping?

**Comment by guelfey** [comment]
Not as easily at least. Eavesdrop explicitly reroutes all messages through the channel that you passed to it - this also includes the method reply message that would be processed under the hood to make `Cal` return normally. You can use `(*object).Go` and then read messages from the `Eavesdrop` channel. But in your case, `(*Conn).Signal` should actually be sufficient to get the signal you need without intercepting method replies.

**Comment by AdamantGarth** [comment]
Thank you! Yeah, `(*Conn).Signal` is a much better solution. But it seems like I need to do something else, besides replacing:
```go
c := make(chan *dbus.Message, 10)
conn.Eavesdrop(c)
```
with:
```go
c := make(chan *dbus.Signal, 10)
conn.Signal(c)
```
Because I don't get any messages this way :(

**Comment by guelfey** [comment]
Ah sorry, I didn't read your use case carefully enough. If `org.freedesktop.Notifications.ActionInvoked` is indeed a unicast and has a destination set that isn't your program, then it will be dropped unless `Eavesdrop` is used, and `Signal` is not enough
