### ISSUE TITLE
CI: Set minimal permissions on GitHub Workflow

### ISSUE THREAD

**Issue by diogoteles08** [godbus/dbus#357]
Hi!

I'm Diogo and I work on Google's Open Source Security Team([GOSST](https://github.com/diogoteles08#about-gosst-ghost)) in cooperation with the Open Source Security Foundation ([OpenSSF](https://openssf.org/)). My core job is to suggest and implement security changes on widely used open source projects 😊

I'm here to suggest the definition of minimal permissions on your workflow, as it would harden your security agains supply-chain attacks. I see that you have only one workflow, the [test.yml](https://github.com/godbus/dbus/blob/master/.github/workflows/test.yml), but it does not specify the permissions for its jobs, letting their privileges determined by GitHub's defaults. By defining minimal permissions you would be secured against erroneous or malicious actions from external jobs you call from your workflow. It's specially important for the case they get compromised, for example.

Setting minimum permissions for workflows is recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and also by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

I'd be happy to raise a PR with the changes if you agree.

**Comment by guelfey** [comment]
Thanks! Adressed in https://github.com/godbus/dbus/pull/360 - I guess that's the minimal set of permissions for a workflow that only really needs to check out the actual Git code.

**Comment by diogoteles08** [comment]
Yep, that definitely addresses the issue. Thanks!
