### ISSUE TITLE
ObjectManager support

### ISSUE THREAD

**Issue by krthy1728** [godbus/dbus#381]
Hello
    I am trying to use GetManagedObjects() method and got an error message saying that ObjectManager is not supported. I checked the issues list and saw an issue that was raised in 2017 containing similar request. Can you please tell me if ObjectManager is currently supported?

Thanks

**Comment by guelfey** [comment]
Indeed, see https://github.com/godbus/dbus/issues/57. I currently don't plan to implement this, but would welcome a PR.
