### ISSUE TITLE
Error caused by dbus.Error with invalid name is unhandled

### ISSUE THREAD

**Issue by alexg-axis** [godbus/dbus#396]
I recently debugged an issue where a client would never receive a response from a method call if said method call returned a `dbus.Error`. The client would basically just time out.

I attached a debugger and started looking for the cause and found this:

1. An error is returned when encoding the error

https://github.com/godbus/dbus/blob/e523abc905595cf17fb0001a7d77eaaddfaa216d/transport_unix.go#L204

2. The error bubbles

https://github.com/godbus/dbus/blob/e523abc905595cf17fb0001a7d77eaaddfaa216d/conn.go#L807

3. The error bubbles

https://github.com/godbus/dbus/blob/e523abc905595cf17fb0001a7d77eaaddfaa216d/conn.go#L495

4. The error bubbles

https://github.com/godbus/dbus/blob/e523abc905595cf17fb0001a7d77eaaddfaa216d/conn.go#L503

5. The error is silently dropped

https://github.com/godbus/dbus/blob/e523abc905595cf17fb0001a7d77eaaddfaa216d/conn.go#L511

The cause was that the error's name was not a valid name. It was akin to `failed to perform method` rather than `org.freedesktop.DBus.Error.InvalidArgs`.

For v6 I suggest for that validation to happen in `dbus.NewError`, with an error returned if it fails. But for v5 it would be really nice to surface this error one way or another.

**Comment by guelfey** [comment]
Fair point. The existing code only generates an error reply on FormatError, but the validity check in validateHeader actually returns an InvalidMessageError...

For this specific case, this is straightforward to fix (add to the type switch) such that at least the client receives a reply. But indeed we also had other issues where the "server layer" of the library had no straightforward way to communicate to the application code of the server that it was doing something wrong. In a possible v6 I would anyway try to find a clearer separation between the "high-level" code (the DefaultHandler etc.) and the low-level code that performs the actual message encoding/decoding.
