### ISSUE TITLE
Add Unexport

### ISSUE THREAD

**Issue by firelizzard18** [godbus/dbus#40]
Maybe I'm totally missing something, but I don't see a way to 'unexport' an object

**Comment by kyrofa** [comment]
Export with a nil object on the same path. It's a feature, but I think they forgot to document it :smile: .

**Comment by philips** [comment]
@firelizzard18 @kyrofa want to document it? :)

**Comment by jonboulle** [comment]
We could probably also just do with a simple helper function for this..

**Comment by guelfey** [comment]
is documented as part of https://pkg.go.dev/github.com/godbus/dbus/v5@v5.0.6#Conn.Export
