### ISSUE TITLE
dbus.Store: type mismatch

### ISSUE THREAD

**Issue by DSpeichert** [godbus/dbus#53]
I have a struct with an element  of the following type (Boolean):

``` go
type Boolean bool

func (bit Boolean) UnmarshalJSON(data []byte) error {
    asString := string(data)
    if asString == "1" || asString == "true" || asString == "True" {
        bit = true
    } else if asString == "0" || asString == "false" || asString == "False" || asString == "null" {
        bit = false
    } else {
        fmt.Printf("%+v %+v\n", data, string(data))
        return errors.New(fmt.Sprintf("Boolean unmarshal error: invalid input %s", asString))
    }
    return nil
}
```

When trying to Store() a struct with "Boolean" field type in it, I get:

```
dbus.Store: type mismatch
```

I can't figure out how to get around that.

**Comment by jsouthworth** [comment]
There are a couple of other places where this happens and is non obvious. I'll take a stab at cleaning up the encoder/decoder some more to support the remainder of the go basic types. Uint and int can be converted to uint32 and int32 respectively so doing that conversion makes a much nicer experience for those using it as well. I recently added support for interface{} as variant, and finishing this up would give more complete support for the host language.

**Comment by jsouthworth** [comment]
I've got a prototype for the new Store procedure that fixes this here: https://github.com/jsouthworth/dbus/tree/fix/53. I need to flesh out the tests for Store to ensure the same base behavior as the existing Store to ensure this won't break anyone's use of Store before I kick out a PR for this.
