### ISSUE TITLE
Regression due to fix for #53

### ISSUE THREAD

**Issue by jsouthworth** [godbus/dbus#78]
@izissise reports:
This change breaks stuff, I call a method with the out signature a{oa{sa{sv}}} with
var res map[dbus.ObjectPath]map[string]map[string]dbus.Variant
It worked yesterday and doesn't today with a type mismatch in dbus.go:99

**Comment by jsouthworth** [comment]
@izissise can you test your application with this change?

**Comment by izissise** [comment]
Thanks for the quick reply, and sorry about not writing a proper issue report.
Pulling this pr, I have this error:

> panic: interface conversion: interface {} is reflect.Value, not string

What I'm doing is calling:
```
var res map[dbus.ObjectPath]map[string]map[string]dbus.Variant
dbus.SystemBus().Object("org.bluez", "/").Call("org.freedesktop.DBus.ObjectManager.GetManagedObjects", 0).Store(&res)
```

**Comment by jsouthworth** [comment]
Can you attach the backtrace from that panic? I'm not able to reproduce that problem on my machine. My guess is it is related to the specific types data that bluez is returning on your system. If possible can you send the data as well? This can be retrieved with 'dbus-send' on the CLI or d-feet on a graphical system.

**Comment by jsouthworth** [comment]
You can skip that I found the problem. In my haste to get a fix out I forgot to convert the reflect.Value to an interface before calling MakeVariant.

**Comment by izissise** [comment]
Awesome!, I can confirm you that it works perfectly with this last commit, Thanks a lot ;)
