### ISSUE TITLE
Support for timeout by passing a context?

### ISSUE THREAD

**Issue by mattbostock** [godbus/dbus#82]
Is there any work being done to set timeouts on requests sent to dbus?

If I were to raise a PR to implement this using Go's `context` library, would that be acceptable? The idea is to mitigate against bugs in dbus ([example](https://bugs.freedesktop.org/show_bug.cgi?id=95263)).

**Comment by jsouthworth** [comment]
This sounds like a good addition. A PR implementing this functionality should follow the convention of the Go standard library in adding support for "context" in a backwards compatible way.

**Comment by tmthrgd** [comment]
This was fixed in #106 right?

**Comment by jsouthworth** [comment]
Yep fixed in #106
