### ISSUE TITLE
Error:  dbus: wire format error: unexpected EOF

### ISSUE THREAD

**Issue by surlykke** [godbus/dbus#85]
Hello

Getting a property with signature (sa(iiay)ss) produces:

`Error:  dbus: wire format error: unexpected EOF`

I've attached a small client and server to reproduce.
I'm pretty sure the problem is on the client side. I've also attached a small script that uses dbus-send to retrieve the property from the server, which works fine.
I came across the problem trying (from go) to retrieve properties from a StatusNotifierItem service written in C++/Qt

br. Chr.

[clientserver.zip](https://github.com/godbus/dbus/files/1034364/clientserver.zip)

**Comment by jsouthworth** [comment]
Thank you for the bug report and reproducer. It may be a few weeks before I will have the time to look at this.

**Comment by datenhahn** [comment]
I ran into a similar problem when trying to get NetworkManager connections via DBUS. I tried it with a different DBUS library ( "launchpad.net/~jamesh/go-dbus/trunk" ) and there it works. I created a repo with a minimal sample code showing the working and the non-working godbus example, maybe this helps debugging the issue:

https://github.com/datenhahn/godbus-debug

![auswahl_179](https://user-images.githubusercontent.com/13999666/31942769-c0da8b8e-b8c6-11e7-84b3-5e0cd5974def.png)
![auswahl_180](https://user-images.githubusercontent.com/13999666/31942771-c4d6be7e-b8c6-11e7-893a-87c5f8e6bcd1.png)
