### ISSUE TITLE
Example for getting a property?

### ISSUE THREAD

**Issue by chrissnell** [godbus/dbus#93]
Hi,

I'm trying to fetch a single property on a DBus object and not having any luck.  Here's a command-line example of what I'm trying to do:

```
% gdbus call -y -d org.freedesktop.resolve1 -o /org/freedesktop/resolve1/link/_32 -m org.freedesktop.DBus.Properties.Get org.freedesktop.resolve1.Link DNS
(<[(2, [byte 0x08, 0x08, 0x08, 0x08]), (2, [0x08, 0x08, 0x04, 0x04])]>,)
```
Here's my non-working code:

```go
	conn, err := dbus.SessionBus()
	if err != nil {
		fmt.Fprintln(os.Stderr, "Failed to connect to session bus:", err)
		os.Exit(1)
	}

	bo := conn.Object("org.freedesktop.resolve1.Manager", "/org/freedesktop/resolve1/link/_32")
	variant, err := bo.GetProperty("DNS")

	if err != nil {
		log.Fatalln("Error getting property:", err)
	}

	log.Println("Variant --->", variant.String)
```

Could you help me with a simple example for fetching a property from an object?   I don't see anything like this in the `_examples` directory.  Thanks.

**Comment by r4zzz4k** [comment]
You should prepend property name with interface name, i.e."
```go
bo.GetProperty("rg.freedesktop.resolve1.Manager.DNS")
```
I'm working out this stuff myself, so if I have some code to share, I'll contribute a bit more involved example.

**Comment by chrissnell** [comment]
I finally figured this out.  There were two problems.  First, as you pointed out, I needed to put the interface name before the property.  Second problem: I was using a session bus instead of the system bus that I needed.

Here's my now-working code:

```
	conn, err := dbus.SystemBus()
	if err != nil {
		fmt.Fprintln(os.Stderr, "Failed to connect to session bus:", err)
		os.Exit(1)
	}

	bo := conn.Object("org.freedesktop.resolve1", "/org/freedesktop/resolve1/link/_32")

	variant, err := bo.GetProperty("org.freedesktop.resolve1.Link.DNS")

	if err != nil {
		log.Fatalln("Error getting property:", err)
	}

	log.Println("Variant --->", variant.String())
```
