### ISSUE TITLE
Possible deadlock (race) when receiving signals during close

### ISSUE THREAD

**Issue by purpleidea** [godbus/dbus#94]
AIUI there's a possible deadlock race when receiving signals during close. I didn't trigger this yet, it is from reading code only. I might be completely misunderstanding everything. Here's the logic:

The signals from `conn.Signal(someChan)` are sent to that user provided channel here:

https://github.com/godbus/dbus/blob/a389bdde4dd695d414e47b755e95e72b7826432c/default_handler.go#L246

If we use an unbuffered channel, or a channel who has a full buffer, we might block on that line, and if we simultaneously try to run `RemoveSignal` or `conn.Close()` then we've deadlocked.

I think the solution is to change that send into a:

```
select {
	case ch <- signal:
		// send
	case sh.closeChan:
		return
}
```

And to implement a `closeChan struct{}` that gets a `close()` called on it whenever we need to unblock and shutdown. It might also be important to consider doing something similar for the `RemoveSignal` function, but I haven't looked into that code path as much.

This is related to https://github.com/godbus/dbus/issues/8 and possibly also: https://github.com/godbus/dbus/issues/1

If you'd like to work on this issue and would like mentorship, please ping @purpleidea here or in #mgmtconfig on Freenode IRC.

Note: this issue came up here: https://github.com/purpleidea/mgmt/blob/677cdea99de89572c4527406204a0a0169560bf5/resources/nspawn.go#L179

Thanks!
// cc @jonathangold

**Comment by purpleidea** [comment]
I think this has regressed. @amenzhinsky seems to have added some things that might have broken this according to git blame. Please see: https://github.com/purpleidea/mgmt/issues/508#issuecomment-498845177

/cc @ffrank

**Comment by amenzhinsky** [comment]
@purpleidea I'm looking at it.

**Comment by purpleidea** [comment]
@amenzhinsky Much appreciated, thanks.

**Comment by amenzhinsky** [comment]
@purpleidea I've submitted a MR to fix this, can you check if it fixes your issue?
