### ISSUE TITLE
Proposal: new release v4.0.1 (to include fixes for some issues)

### ISSUE THREAD

**Issue by ghouscht** [godbus/dbus#95]
Hi there,
I'm using godbus/dbus quite successfully in a few projects. I had some issues with panics (send on closed channel) sometimes (quite rare). 

So I did some research and found this issue: #45 which seems to be exactly the problem I got. The issue was fixed quite a long time ago and I was wondering why it still hit me. 
I'am using "glide" or "dep" to vendor all my projects and found out that I'm using the latest release (which currently is v4.0.0, released 19 Apr 2016). Unfortunately this release does not include the fix for issue #45. 

To beware future users of godbus/dbus (using vendoring tools and using releases, which I think is the wiedly used standard) making the same mistake like me I'd like to propose publishing a new minor release v4.0.1.

Thank you for your work and regards,
Thomas

**Comment by jsouthworth** [comment]
Hi Thomas,

I can get this taken care of for you. It looks like I might have to pull a v4 branch and then do a v4.0.1 release. We can then backport other fixes if required into v4. Github doesn't seem to want to let me release from the commit before the major changes went in. I'll then do a v5.0.0 release with the current code as it is now stable. I'm not familiar with the vendoring workflow, I'm still packaging this up into debian packages to build our product. Does what I've outlined above follow the desired workflow? 

Regards,
John

**Comment by jsouthworth** [comment]
I suppose that the work that has been done is more like a v4.1.0 since the API hasn't changed.

**Comment by jsouthworth** [comment]
I've released the current changes as v4.1.0
