### ISSUE TITLE
Can't understand examples

### ISSUE THREAD

**Issue by arpitjindal97** [godbus/dbus#96]
I have been scratching my head since yesterday but can't figure how to use this library. 

Examples given in the repository aren't understandable. Can anyone please tell me how to communicate to `wpa_supplicant` ?

I just need a simple example of `CreateInterface` in wpa_supplicant.

https://w1.fi/wpa_supplicant/devel/dbus.html#dbus_main

I have also asked this question on [StackOverflow](https://stackoverflow.com/questions/48358457/how-to-use-dbus-with-golang)

**Comment by jsouthworth** [comment]
One has to know the DBus semantics to really understand the documentation. Some things cold be clarified to make this easier.

Something like this should work:
```
package main

import (
	"github.com/godbus/dbus"
	"log"
)

func main() {
	conn, err := dbus.SystemBus()
	if err != nil {
		log.Fatal(err)
	}
	obj := conn.Object("fi.w1.wpa_supplicant1", //Well known name on the bus (busctl list will show these)
		dbus.ObjectPath("/fi/w1/wpa_supplicant1")) //Object path (busctl tree well known name shows these)

	//Method name is the interface + the method name
	//a{sv} is the same as map[string]interface{}
	//o is the same as dbus.ObjectPath
	var intfPath dbus.ObjectPath
	err = obj.Call("fi.w1.wpa_supplicant1.CreateInterface", 0, map[string]interface{}{
		"Ifname": "wlan0",
		"Driver": "nl80211",
	}).Store(&intfPath)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(intfPath)
}
```

**Comment by arpitjindal97** [comment]
This guy @jsouthworth is living angel. You solved all of queries in few minutes. 
Really appreciate you for taking out time to answer me. 

Thank you

**Comment by arpitjindal97** [comment]
I have just one more query. After having successfully created interface in wpa, I want to read all the signals from that interface eg. Disconnected from Network, Connected, Authorized. 

There is `State` property of `/fi/w1/wpa_supplicant1/Interfaces/0` which is what i want but 
I don't want to do polling for it.


There are few signal 

`busctl introspect fi.w1.wpa_supplicant1 /fi/w1/wpa_supplicant1/Interfaces/0`

```
.BSSAdded                                 signal    oa{sv}   
.BSSRemoved                               signal    o  
.BlobAdded                                signal    s       
.BlobRemoved                              signal    s      
.Certification                            signal    a{sv}   
.EAP                                      signal    ss       
.NetworkAdded                             signal    oa{sv}   
.NetworkRemoved                           signal    o       
.NetworkRequest                           signal    oss      
.NetworkSelected                          signal    o      
.ProbeRequest                             signal    a{sv}   
.PropertiesChanged                        signal    a{sv}  
.ScanDone                                 signal    b    
.StaAuthorized                            signal    s       
.StaDeauthorized                          signal    s    
```

Can you please tell me how can i read signals ? And what will be the best way to capture those events.

How does `NetworkManager` come to know about the state change, does it polls or read signals ?

**Comment by jsouthworth** [comment]
First you need to inform the bus of the signal you want to receive. [AddMatch](https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-add-match) has the full details. You didn't provide enough output in the question (and I don't have a box with a wifi device to play with at the moment) but this should get you started:
```
conn.BusObject().Call("org.freedesktop.DBus.AddMatch", 0, "'type='signal',path='/fi/w1/wpa_supplicant1/Interfaces/0',interface='<interface-name-that-signals-are-part-of>'")
```
Then you use the conn.Signal to attach a channel to have the signals appear on:
```
ch := make(chan *dbus.Signal, 10)
conn.Signal(ch)
for sig := range ch {
     //do something with signal. sig.Name can be used to dispatch for decoding. You can use dbus.Store(sig.Body, &val) to decode the body into a data-structure the same way as you use .Store on a Call.
}
```

**Comment by jsouthworth** [comment]
If things are complex enough you can also replace the default signal handler with your own code using DialHandler and passing in an object that meets the SignalHandler interface. This will be synchronous delivery until you make it a synchronous (spawn a go routine send to a channel etc.)

**Comment by arpitjindal97** [comment]
Although I didn't understand your 2nd comment but the signal code did the job.

Thanks for your time.
