### ISSUE TITLE
unixTransport.ReadMessage doesn't handle array of Unix FDs

### ISSUE THREAD

**Issue by svenschwermer** [godbus/dbus#99]
If one of the message body's fields is an array of file descriptors, this is not handled properly. Instead of replacing the indices, they remain untouched. I noticed this when I tried to invoke `CreateConnection` from this interface: https://github.com/tpm2-software/tpm2-abrmd/blob/master/src/tabrmd.xml

**Comment by savely-krasovsky** [comment]
For some unknown reason, the tpm2-abrmd developers removed parameters that were necessary for godbus to return an FD. You need to apply this patch in order to access it: #432.
